/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 *
 * @author bests
 */
import javax.swing.JOptionPane;
import java.util.List;
import Model.Produk;
import Model.Kategori;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.DefaultListSelectionModel;

public class DialogTambahProduk extends javax.swing.JDialog {
    private int idToko;
    private DAO.ProdukDAO pDao = new DAO.ProdukDAO();
    private DAO.KategoriDAO kDao = new DAO.KategoriDAO();
    
    private final String PLACEHOLDER_NAMA = "Masukkan nama produk";
    private final String PLACEHOLDER_HARGA = "Masukkan harga produk";
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogTambahProduk.class.getName());

    /**
     * Creates new form DialogTambahProduk
     */
    public DialogTambahProduk(java.awt.Frame parent, boolean modal, int idToko) {
        super(parent, modal);
        this.idToko = idToko;
        initComponents();
        
        setupToggleSelection(); 
        setupPlaceholders();
        loadKategori();
        
        btnTambahProduk.requestFocusInWindow();
        
        this.setLocationRelativeTo(parent);
    }

// --- FITUR 1: TOGGLE SELECTION UNTUK LIST KATEGORI ---
    // User bisa klik item untuk pilih/batal tanpa tekan Ctrl
    private void setupToggleSelection() {
        ListKategori.setSelectionModel(new DefaultListSelectionModel() {
            @Override
            public void setSelectionInterval(int index0, int index1) {
                if (super.isSelectedIndex(index0)) {
                    super.removeSelectionInterval(index0, index1);
                } else {
                    super.addSelectionInterval(index0, index1);
                }
            }
        });
    }

    // --- FITUR 2: TOGGLE PLACEHOLDER TEKS ---
    private void setupPlaceholders() {
        // SET TEKS AWAL (Penting karena teks di GUI sudah dihapus)
        txtNama.setText(PLACEHOLDER_NAMA);
        txtNama.setForeground(Color.GRAY);
        
        txtHarga.setText(PLACEHOLDER_HARGA);
        txtHarga.setForeground(Color.GRAY);
        
        txtNama.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtNama.getText().equals(PLACEHOLDER_NAMA)) {
                    txtNama.setText("");
                    txtNama.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (txtNama.getText().isEmpty()) {
                    txtNama.setText(PLACEHOLDER_NAMA);
                    txtNama.setForeground(Color.GRAY);
                }
            }
        });

        txtHarga.setForeground(Color.GRAY);
        txtHarga.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (txtHarga.getText().equals(PLACEHOLDER_HARGA)) {
                    txtHarga.setText("");
                    txtHarga.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (txtHarga.getText().isEmpty()) {
                    txtHarga.setText(PLACEHOLDER_HARGA);
                    txtHarga.setForeground(Color.GRAY);
                }
            }
        });
    }    
    
    private void loadKategori() {
        javax.swing.DefaultListModel<String> model = new javax.swing.DefaultListModel<>();
        try {
            List<Model.Kategori> list = kDao.getAllKategori(this.idToko);
            for (Model.Kategori k : list) {
                model.addElement(k.getNamaKategori()); // Tambahkan ke model list
            }
            ListKategori.setModel(model); // Set model ke JList
        } catch (Exception e) {
            System.err.println("Gagal load kategori: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnExit = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lblHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        lblKategori = new javax.swing.JLabel();
        btnTambahProduk = new javax.swing.JButton();
        btnBatalTambah = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListKategori = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHeader.setText("Tambah Produk Baru");

        btnExit.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblNama.setText("Nama Produk");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        lblHarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblHarga.setText("Harga (Rp.)");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });

        lblKategori.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblKategori.setText("Kategori (pilih 1 atau lebih)");

        btnTambahProduk.setText("TAMBAH PRODUK");
        btnTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProdukActionPerformed(evt);
            }
        });

        btnBatalTambah.setText("BATAL");
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });

        ListKategori.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListKategori);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(15, 15, 15))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                .addComponent(lblNama)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblKategori)
                                        .addComponent(lblHarga))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBatalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnTambahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(lblHeader))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblKategori)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatalTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        btnTambahProdukActionPerformed(evt);
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProdukActionPerformed
        try {
            String nama = txtNama.getText().trim();
            String hargaRaw = txtHarga.getText().trim();

            // VALIDASI: Cek apakah user belum mengisi (masih placeholder)
            if (nama.equals(PLACEHOLDER_NAMA) || nama.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama produk harus diisi!");
                return;
            }
            if (hargaRaw.equals(PLACEHOLDER_HARGA) || hargaRaw.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Harga produk harus diisi!");
                return;
            }

            double harga = Double.parseDouble(hargaRaw);

            // Logika ambil kategori dan simpan (Sudah Benar)
            List<String> kategoriTerpilih = ListKategori.getSelectedValuesList();
            if (kategoriTerpilih.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pilih minimal satu kategori!");
                return;
            }

            Produk p = new Produk(this.idToko, nama, harga);
            for (String namaKat : kategoriTerpilih) {
                int idKat = kDao.getIdByName(namaKat, this.idToko);
                Kategori kat = new Kategori(idKat, namaKat, this.idToko);
                p.getDaftarKategori().add(kat); 
            }

            pDao.tambahProduk(p);
            JOptionPane.showMessageDialog(this, "Produk Berhasil Disimpan!");
            this.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka yang valid!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahProdukActionPerformed

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalTambahActionPerformed

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        char c = evt.getKeyChar();
        // Hanya izinkan angka, titik (untuk double), dan tombol backspace
        if (!(Character.isDigit(c) || c == java.awt.event.KeyEvent.VK_BACK_SPACE || c == '.')) {
            evt.consume(); // Abaikan input jika bukan angka/titik
        }

        // Cegah titik ganda untuk tipe data double
        if (c == '.' && txtHarga.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHargaKeyTyped

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogTambahProduk dialog = new DialogTambahProduk(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListKategori;
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTambahProduk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
