/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author bests
 */

import DAO.ProdukDAO;
import DAO.KategoriDAO;
import DAO.TokoDAO;
import Model.Produk;
import Model.Kategori;
import Model.Toko;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrameOperasional extends javax.swing.JFrame {
    private int idToko;
    private ProdukDAO pDao = new ProdukDAO();
    private KategoriDAO kDao = new KategoriDAO();
    private TokoDAO tDao = new TokoDAO();
    
    public FrameOperasional(int idToko) {
        this.idToko = idToko;
        initComponents();
        this.setLocationRelativeTo(null);
        loadDetailToko();    // Menampilkan info toko di label header
        loadTabelProduk();   // Isi tabel produk
        loadTabelKategori(); // Isi tabel kategori
    }
    
    private void loadDetailToko() {
        try {
            Toko t = tDao.getTokoById(this.idToko);
            if (t != null) {
                lblNamaToko.setText(t.getNamaToko());
                lblIdToko.setText("ID : " + t.getIdToko());
                lblAlamatToko.setText("Alamat : " + t.getAlamatToko());
                lblPemilikToko.setText("Pemilik : " + t.getPemilikToko());
            }
        } catch (Exception e) {
            System.err.println("Gagal load detail toko: " + e.getMessage());
        }
    }
    
    public void loadTabelProduk() {
        // 1. Definisikan header dengan 5 kolom (No, ID, Nama, Kategori, Harga)
    String[] header = {"No", "ID Produk", "Nama Produk", "Kategori", "Harga"};
    DefaultTableModel model = new DefaultTableModel(header, 0) {
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    };

    try {
        List<Produk> list = pDao.getAllProduk(this.idToko);
        int no = 1;
        for (Produk p : list) {
            // 2. Masukkan data sesuai urutan header (Kategori di index 3)
            Object[] row = {
                no++, 
                p.getIdProduk(), 
                p.getNamaProduk(), 
                p.getKategoriTampilan(), // Data dari GROUP_CONCAT di DAO
                p.getHarga()
            };
            model.addRow(row);
        }
        tblProduk.setModel(model);

        // 3. Atur Lebar Kolom agar rapi
        tblProduk.getColumnModel().getColumn(0).setPreferredWidth(40); // No
        tblProduk.getColumnModel().getColumn(1).setPreferredWidth(70); // ID
        tblProduk.getColumnModel().getColumn(2).setPreferredWidth(150); // Nama
        tblProduk.getColumnModel().getColumn(3).setPreferredWidth(150); // Kategori
        tblProduk.getColumnModel().getColumn(4).setPreferredWidth(100); // Harga
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load produk: " + e.getMessage());
    }
    }
    
    public void loadTabelKategori() {
        // Menambahkan kolom "No" di index 0
        String[] header = {"No", "ID Kategori", "Nama Kategori"};
        DefaultTableModel model = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int row, int column) { return false; }
        };

        try {
            List<Kategori> list = kDao.getAllKategori(this.idToko);
            int no = 1;
            for (Kategori k : list) {
                Object[] row = {no++, k.getIdKategori(), k.getNamaKategori()};
                model.addRow(row);
            }
            tblKategori.setModel(model);

            // Atur Lebar Kolom
            tblKategori.getColumnModel().getColumn(0).setPreferredWidth(35);
            tblKategori.getColumnModel().getColumn(0).setMaxWidth(50);
            tblKategori.getColumnModel().getColumn(1).setPreferredWidth(70); // ID Kategori
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load kategori: " + e.getMessage());
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameOperasional.class.getName());

    /**
     * Creates new form FrameOperasional
     */
    public FrameOperasional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabUtama = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        lblNamaToko1 = new javax.swing.JLabel();
        btnEditProduk = new javax.swing.JButton();
        btnTambahProduk = new javax.swing.JButton();
        btnHapusProduk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();
        lblNamaToko2 = new javax.swing.JLabel();
        btnEditKategori = new javax.swing.JButton();
        btnTambahKategori = new javax.swing.JButton();
        btnHapusKategori = new javax.swing.JButton();
        lblNamaToko = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblIdToko = new javax.swing.JLabel();
        lblIdToko1 = new javax.swing.JLabel();
        lblAlamatToko = new javax.swing.JLabel();
        lblIdToko3 = new javax.swing.JLabel();
        lblPemilikToko = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "ID Produk", "Nama Produk", "Kategori", "Harga"
            }
        ));
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduk);
        if (tblProduk.getColumnModel().getColumnCount() > 0) {
            tblProduk.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        lblNamaToko1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNamaToko1.setText("Daftar Produk");

        btnEditProduk.setText("Edit");
        btnEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProdukActionPerformed(evt);
            }
        });

        btnTambahProduk.setText("Tambah Produk");
        btnTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProdukActionPerformed(evt);
            }
        });

        btnHapusProduk.setText("Hapus");
        btnHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNamaToko1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambahProduk)
                        .addGap(12, 12, 12)
                        .addComponent(btnEditProduk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusProduk))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaToko1)
                    .addComponent(btnEditProduk)
                    .addComponent(btnTambahProduk)
                    .addComponent(btnHapusProduk))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        tabUtama.addTab("Produk", jPanel1);

        tblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "ID Kategori", "Nama Kategori"
            }
        ));
        tblKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKategoriMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKategori);
        if (tblKategori.getColumnModel().getColumnCount() > 0) {
            tblKategori.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        lblNamaToko2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblNamaToko2.setText("Daftar Kategori");

        btnEditKategori.setText("Edit");
        btnEditKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditKategoriActionPerformed(evt);
            }
        });

        btnTambahKategori.setText("Tambah Kategori");
        btnTambahKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKategoriActionPerformed(evt);
            }
        });

        btnHapusKategori.setText("Hapus");
        btnHapusKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNamaToko2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambahKategori)
                        .addGap(12, 12, 12)
                        .addComponent(btnEditKategori)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusKategori))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaToko2)
                    .addComponent(btnEditKategori)
                    .addComponent(btnTambahKategori)
                    .addComponent(btnHapusKategori))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        tabUtama.addTab("Kategori", jPanel2);

        lblNamaToko.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNamaToko.setText("Nama Toko");

        lblIdToko.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblIdToko.setText("ID : -");

        lblIdToko1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblIdToko1.setText("|");

        lblAlamatToko.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAlamatToko.setText("Alamat : -");

        lblIdToko3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblIdToko3.setText("|");

        lblPemilikToko.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPemilikToko.setText("Pemilik : -");

        btnKembali.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        btnKembali.setText("X");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdToko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdToko1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlamatToko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdToko3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPemilikToko)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNamaToko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)
                        .addGap(15, 15, 15))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaToko)
                    .addComponent(btnKembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdToko)
                    .addComponent(lblIdToko1)
                    .addComponent(lblAlamatToko)
                    .addComponent(lblIdToko3)
                    .addComponent(lblPemilikToko))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProdukActionPerformed
        // Buka Dialog Tambah Produk dengan melempar ID Toko
        DialogTambahProduk dialog = new DialogTambahProduk(FrameOperasional.this, true, this.idToko);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // Refresh tabel setelah dialog ditutup
        loadTabelProduk();
    }//GEN-LAST:event_btnTambahProdukActionPerformed

    private void btnTambahKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKategoriActionPerformed
        DialogTambahKategori dialog = new DialogTambahKategori(this, true, this.idToko);
        dialog.setVisible(true);
        loadTabelKategori();
    }//GEN-LAST:event_btnTambahKategoriActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new FrameToko().setVisible(true); // Ganti 'FrameUtama' dengan nama frame utama Anda
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked
        if (evt.getClickCount() == 2) {
            btnEditProdukActionPerformed(null);
        }
    }//GEN-LAST:event_tblProdukMouseClicked

    private void btnEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProdukActionPerformed
       int row = tblProduk.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih produk pada tabel yang ingin diedit!");
            return;
        }

        try {
            int id = Integer.parseInt(tblProduk.getValueAt(row, 1).toString());
            String nama = tblProduk.getValueAt(row, 2).toString();
            double harga = Double.parseDouble(tblProduk.getValueAt(row, 4).toString());

            Produk p = new Produk();
            p.setIdProduk(id);
            p.setNamaProduk(nama);
            p.setHarga(harga);

            // --- TAMBAHKAN BAGIAN INI ---
            // Kita ambil daftar kategori asli dari database berdasarkan ID Produk
            // Pastikan pDao memiliki method getKategoriByProdukId
            List<Kategori> daftarKategori = pDao.getKategoriByProdukId(id);
            p.setDaftarKategori(daftarKategori); 
            // ----------------------------

            DialogEditProduk dialog = new DialogEditProduk(this, true, this.idToko, p);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            loadTabelProduk();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memproses data edit: " + e.getMessage());
            e.printStackTrace(); // Agar kamu bisa lihat error detail di console
        }

    }//GEN-LAST:event_btnEditProdukActionPerformed

    private void btnHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusProdukActionPerformed
        int row = tblProduk.getSelectedRow();
    
        if (row != -1) {
            // Ambil ID dari index 1, Nama dari index 2
            int id = Integer.parseInt(tblProduk.getValueAt(row, 1).toString());
            String nama = tblProduk.getValueAt(row, 2).toString();

            int konfirmasi = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin ingin menghapus produk '" + nama + "'?", 
                    "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    pDao.deleteProduk(id);
                    JOptionPane.showMessageDialog(this, "Produk berhasil dihapus!");
                    loadTabelProduk();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal hapus produk: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih produk yang ingin dihapus terlebih dahulu!");
        }
    }//GEN-LAST:event_btnHapusProdukActionPerformed

    private void tblKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKategoriMouseClicked
        if (evt.getClickCount() == 2) {
            btnEditKategoriActionPerformed(null);
        }
    }//GEN-LAST:event_tblKategoriMouseClicked

    private void btnEditKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKategoriActionPerformed
        int selectedRow = tblKategori.getSelectedRow();
    
        if (selectedRow != -1) {
            // PERBAIKAN: Ambil dari index 1 (ID), bukan index 0 (No)
            int idKategori = Integer.parseInt(tblKategori.getValueAt(selectedRow, 1).toString());
            // PERBAIKAN: Nama ada di index 2
            String namaKategori = tblKategori.getValueAt(selectedRow, 2).toString();

            DialogEditKategori dialog = new DialogEditKategori(this, true, idKategori, namaKategori);
            dialog.setVisible(true);
            loadTabelKategori();
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih kategori terlebih dahulu!");
        }
    }//GEN-LAST:event_btnEditKategoriActionPerformed

    private void btnHapusKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKategoriActionPerformed
        int row = tblKategori.getSelectedRow();
        if (row != -1) {
            // PERBAIKAN: Ambil ID dari index 1
            int id = Integer.parseInt(tblKategori.getValueAt(row, 1).toString());
            // PERBAIKAN: Ambil Nama dari index 2
            String nama = tblKategori.getValueAt(row, 2).toString();

            int konfirmasi = JOptionPane.showConfirmDialog(this, "Hapus kategori '" + nama + "'?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (konfirmasi == JOptionPane.YES_OPTION) {
                try {
                    kDao.deleteKategori(id);
                    loadTabelKategori();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnHapusKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameOperasional().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditKategori;
    private javax.swing.JButton btnEditProduk;
    private javax.swing.JButton btnHapusKategori;
    private javax.swing.JButton btnHapusProduk;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambahKategori;
    private javax.swing.JButton btnTambahProduk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAlamatToko;
    private javax.swing.JLabel lblIdToko;
    private javax.swing.JLabel lblIdToko1;
    private javax.swing.JLabel lblIdToko3;
    private javax.swing.JLabel lblNamaToko;
    private javax.swing.JLabel lblNamaToko1;
    private javax.swing.JLabel lblNamaToko2;
    private javax.swing.JLabel lblPemilikToko;
    private javax.swing.JTabbedPane tabUtama;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTable tblProduk;
    // End of variables declaration//GEN-END:variables
}
