/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author bests
 */

import DAO.TokoDAO;
import Model.Toko;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class FrameToko extends javax.swing.JFrame {
    private TokoDAO tokoDao = new TokoDAO();
    private DefaultTableModel model;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameToko.class.getName());

    /**
     * Creates new form FrameToko
     */
    public FrameToko() {
        initComponents();
        loadData();
    }
    
    private void loadData() {
        // 1. Tambahkan "No" ke dalam header
        String[] header = {"No", "ID", "Nama Toko", "Alamat", "Pemilik"};

        model = new DefaultTableModel(header, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Menonaktifkan edit langsung
            }
        };

        try {
            List<Toko> daftar = tokoDao.getAllToko();
            int noUrut = 1; // Inisialisasi penghitung nomor

            for (Toko t : daftar) {
                // 2. Masukkan noUrut ke index 0, dan geser data lainnya
                Object[] row = {
                    noUrut++, 
                    t.getIdToko(), 
                    t.getNamaToko(), 
                    t.getAlamatToko(), 
                    t.getPemilikToko()
                };
                model.addRow(row);
            }
            TblToko.setModel(model);
            
            aturLebarKolom();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    
    private void aturLebarKolom() {
    // Kolom "No" (Index 0) dibuat sempit
    TblToko.getColumnModel().getColumn(0).setPreferredWidth(35);
    TblToko.getColumnModel().getColumn(0).setMaxWidth(50);
    
    // Kolom "ID" (Index 1) juga dibuat agak sempit
    TblToko.getColumnModel().getColumn(1).setPreferredWidth(50);
    TblToko.getColumnModel().getColumn(1).setMaxWidth(70);
    
    // Kolom sisanya akan menyesuaikan secara otomatis
    }
    
    private void clearFields() {
        txtNamaToko.setText("");
        txtAlamatToko.setText("");
        txtNamaPemilik.setText("");
        TblToko.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblToko = new javax.swing.JTable();
        txtNamaToko = new javax.swing.JTextField();
        txtAlamatToko = new javax.swing.JTextField();
        txtNamaPemilik = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKelola = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        lblTitle4 = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTitle.setText("Daftar Toko Tersedia");

        TblToko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "ID Toko", "Nama Toko", "Alamat", "Pemilik"
            }
        ));
        TblToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblTokoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblToko);
        if (TblToko.getColumnModel().getColumnCount() > 0) {
            TblToko.getColumnModel().getColumn(0).setPreferredWidth(20);
            TblToko.getColumnModel().getColumn(1).setPreferredWidth(40);
        }

        txtNamaToko.setText("Masukan nama toko");

        txtAlamatToko.setText("Masukan alamat toko");
        txtAlamatToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatTokoActionPerformed(evt);
            }
        });

        txtNamaPemilik.setText("Masukan nama pemilik");
        txtNamaPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPemilikActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKelola.setText("Kelola");
        btnKelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitle1.setText("MANAJEMEN TOKO");

        lblTitle2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTitle2.setText("Tambah Toko Baru");

        lblTitle3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblTitle3.setText("Nama Toko");

        lblTitle4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblTitle4.setText("Alamat Toko");

        lblTitle5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblTitle5.setText("Pemilik Toko");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle1)
                .addGap(233, 233, 233))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnKelola, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle3)
                    .addComponent(lblTitle2)
                    .addComponent(txtNamaToko)
                    .addComponent(txtAlamatToko)
                    .addComponent(txtNamaPemilik, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(lblTitle4)
                    .addComponent(lblTitle5)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle1)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblTitle2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaToko, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlamatToko, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTitle5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaPemilik))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnKelola)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = TblToko.getSelectedRow();
        if (row != -1) {
            try {
                int id = (int) TblToko.getValueAt(row, 0);
                Toko tokoUpdate = new Toko(id, txtNamaToko.getText(), txtAlamatToko.getText(), txtNamaPemilik.getText());
                tokoDao.updateToko(tokoUpdate);
                JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui!");
                loadData(); // Refresh tabel
                clearFields();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal Update: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel terlebih dahulu!");
        }    
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = TblToko.getSelectedRow();
        if (row != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus toko ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    int id = (int) TblToko.getValueAt(row, 0);
                    tokoDao.deleteToko(id);
                    loadData(); // Refresh tabel
                    clearFields();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data di tabel yang ingin dihapus!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaActionPerformed
        int row = TblToko.getSelectedRow();

        if (row != -1) {
            try {
                // PERBAIKAN: Ambil dari index 1 (Kolom ID), bukan index 0 (Kolom No)
                int idToko = (int) TblToko.getValueAt(row, 1);

                FrameOperasional operasional = new FrameOperasional(idToko);
                operasional.setVisible(true);
                this.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal membuka menu operasional: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih toko dari tabel terlebih dahulu untuk dikelola!");
        }
    }//GEN-LAST:event_btnKelolaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            String nama = txtNamaToko.getText();
            String alamat = txtAlamatToko.getText();
            String pemilik = txtNamaPemilik.getText();

            if (nama.isEmpty() || alamat.isEmpty() || pemilik.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua input harus diisi!");
                return;
            }

            // PERBAIKAN: Tangkap ID yang dikembalikan (int)
            int idTokoBaru = tokoDao.tambahToko(nama, alamat, pemilik);

            JOptionPane.showMessageDialog(this, "Toko Berhasil Ditambahkan dengan ID: " + idTokoBaru);
            loadData(); // Refresh tabel agar ID muncul di tabel
            clearFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Tambah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void TblTokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblTokoMouseClicked
        int row = TblToko.getSelectedRow();
        if (row != -1) {
            // PERBAIKAN: Index disesuaikan dengan kolom di loadData()
            // Index 1 = Nama, Index 2 = Alamat, Index 3 = Pemilik
            txtNamaToko.setText(TblToko.getValueAt(row, 2).toString());
            txtAlamatToko.setText(TblToko.getValueAt(row, 3).toString());
            txtNamaPemilik.setText(TblToko.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_TblTokoMouseClicked

    private void txtAlamatTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatTokoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatTokoActionPerformed

    private void txtNamaPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPemilikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameToko().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblToko;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKelola;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JTextField txtAlamatToko;
    private javax.swing.JTextField txtNamaPemilik;
    private javax.swing.JTextField txtNamaToko;
    // End of variables declaration//GEN-END:variables
}
